#!/bin/bash

for i in $(find "$@" -name "*.gpg"); do
  # Print the filename to STDOUT.
  echo "$i"
  # Grab all the header information, push it to STDERR.
  gpg --batch --list-packets "$i" > /dev/null
done
