#!/bin/bash

for i in $(find "$@" -name "*.gpg"); do
  echo "$i"
  gpg --batch --list-packets "$i" > /dev/null
done

#for i in $(find . -name "*.gpg"); do 
#  if [[ $(( gpg --batch --list-packets "$i" 3>&1 2>&3- ) | sed "3q;d") =~ "$@" ]]; then 
#    echo "$i" 
#  fi
#done
